indicaciones = {
    "H200": "Explosivo inestable.",
    "H201": "Explosivo; peligro de explosión en masa.",
    "H202": "Explosivo; grave peligro de proyección.",
    "H203": "Explosivo; peligro de incendio, de onda expansiva o de proyección.",
    "H204": "Peligro de incendio o de proyección.",
    "H205": "Peligro de explosión en masa en caso de incendio.",
    "H220": "Gas extremadamente inflamable.",
    "H221": "Gas inflamable.",
    "H222": "Aerosol extremadamente inflamable.",
    "H223": "Aerosol inflamable.",
    "H224": "Líquido y vapor extremadamente inflamables.",
    "H225": "Líquido y vapor inflamables.",
    "H226": "Líquido y vapor inflamables.",
    "H228": "Sólido inflamable.",
    "H229": "Recipiente a presión: puede reventar si se calienta.",
    "H230": "Puede reaccionar de manera explosiva incluso en ausencia de aire.",
    "H231": "Puede reaccionar de manera explosiva incluso en ausencia de aire.",
    "H240": "Peligro de explosión en caso de calentamiento.",
    "H241": "Peligro de incendio o de explosión en caso de calentamiento.",
    "H242": "Peligro de incendio en caso de calentamiento.",
    "H250": "Se inflama espontáneamente en contacto con el aire.",
    "H251": "Autocalentable; puede inflamarse.",
    "H252": "Autocalentable en grandes cantidades; puede inflamarse.",
    "H260": "Desprende gases inflamables en contacto con el agua, que pueden inflamarse espontáneamente.",
    "H261": "Desprende gases inflamables en contacto con el agua.",
    "H270": "Puede provocar o agravar un incendio; comburente.",
    "H271": "Puede provocar un incendio o una explosión; muy comburente.",
    "H272": "Puede agravar un incendio; comburente.",
    "H280": "Contiene gas a presión; peligro de explosión en caso de calentamiento.",
    "H281": "Contiene gas refrigerado; puede provocar quemaduras o lesiones criogénicas.",
    "H290": "Puede ser corrosivo para los metales.",
    "H300": "Mortal en caso de ingestión.",
    "H301": "Tóxico en caso de ingestión.",
    "H302": "Nocivo en caso de ingestión.",
    "H303": "Puede ser nocivo en caso de ingestión.",
    "H304": "Puede ser mortal en caso de ingestión y penetración en las vías respiratorias.",
    "H305": "Puede ser nocivo en caso de ingestión y penetración en las vías respiratorias.",
    "H310": "Mortal en contacto con la piel.",
    "H311": "Tóxico en contacto con la piel.",
    "H312": "Nocivo en contacto con la piel.",
    "H313": "Puede ser nocivo en contacto con la piel.",
    "H314": "Provoca quemaduras graves en la piel y lesiones oculares graves.",
    "H315": "Provoca irritación cutánea.",
    "H316": "Provoca ligera irritación cutánea.",
    "H317": "Puede provocar una reacción alérgica en la piel.",
    "H318": "Provoca lesiones oculares graves.",
    "H319": "Provoca irritación ocular grave.",
    "H320": "Provoca irritación ocular.",
    "H330": "Mortal en caso de inhalación.",
    "H331": "Tóxico en caso de inhalación.",
    "H332": "Nocivo en caso de inhalación.",
    "H333": "Puede ser nocivo en caso de inhalación.",
    "H334": "Puede provocar síntomas de alergia o asma o dificultades respiratorias en caso de inhalación.",
    "H335": "Puede irritar las vías respiratorias.",
    "H336": "Puede provocar somnolencia o vértigo.",
    "H340": "Puede provocar defectos genéticos.",
    "H341": "Se sospecha que provoca defectos genéticos.",
    "H350": "Puede provocar cáncer.",
    "H351": "Se sospecha que provoca cáncer.",
    "H360": "Puede perjudicar la fertilidad o dañar al feto.",
    "H361": "Se sospecha que puede perjudicar la fertilidad o dañar al feto.",
    "H362": "Puede perjudicar a los niños alimentados con leche materna.",
    "H370": "Provoca daños en los órganos.",
    "H371": "Puede provocar daños en los órganos.",
    "H372": "Provoca daños en los órganos tras exposiciones prolongadas o repetidas.",
    "H373": "Puede provocar daños en los órganos tras exposiciones prolongadas o repetidas.",
    "H400": "Muy tóxico para los organismos acuáticos.",
    "H410": "Muy tóxico para los organismos acuáticos, con efectos duraderos.",
    "H411": "Tóxico para los organismos acuáticos, con efectos duraderos.",
    "H412": "Nocivo para los organismos acuáticos, con efectos duraderos.",
    "H413": "Puede ser nocivo para los organismos acuáticos, con efectos duraderos.",
    "H420": "Perjudica la salud pública y el medio ambiente por destrucción del ozono estratosférico.",
    "P101": "Si se necesita consejo médico, tener a mano el envase o la etiqueta.",
    "P102": "Mantener fuera del alcance de los niños.",
    "P103": "Leer la etiqueta antes del uso.",
    "P201": "Pedir instrucciones especiales antes del uso.",
    "P202": "No manipular antes de haber leído y comprendido todas las instrucciones de seguridad.",
    "P210": "Mantener alejado del calor, de superficies calientes, de chispas, de llamas y de cualquier otra fuente de ignición. No fumar.",
    "P211": "No pulverizar sobre una llama abierta u otra fuente de ignición.",
    "P220": "Mantener o almacenar alejado de ropa, materiales combustibles.",
    "P221": "Tomar todas las precauciones necesarias para no mezclar con materiales combustibles.",
    "P222": "No permitir contacto con el aire.",
    "P223": "Mantener el recipiente herméticamente cerrado.",
    "P230": "Mantener húmedo con... (un líquido apropiado que se especificará).",
    "P231": "Manipular bajo gas inerte.",
    "P232": "Proteger de la humedad.",
    "P233": "Mantener el recipiente herméticamente cerrado.",
    "P234": "Conservar únicamente en el envase original.",
    "P235": "Mantener en lugar fresco.",
    "P240": "Conectar a tierra/enlace equipotencial del recipiente y del equipo de recepción.",
    "P241": "Utilizar un material eléctrico, de ventilación o de iluminación a prueba de explosión.",
    "P242": "Utilizar únicamente herramientas que no produzcan chispas.",
    "P243": "Tomar medidas de precaución contra descargas electrostáticas.",
    "P244": "Mantener las válvulas de reducción de presión y dispositivos de seguridad sin aceite y grasa.",
    "P250": "Evitar aplastamientos/golpes/impactos/roces...",
    "P251": "No perforar ni quemar, incluso después de su uso.",
    "P260": "No respirar el polvo/el humo/el gas/la niebla/los vapores/el aerosol.",
    "P261": "Evitar respirar el polvo/el humo/el gas/la niebla/los vapores/el aerosol.",
    "P262": "Evitar el contacto con los ojos, la piel o la ropa.",
    "P263": "Evitar el contacto durante el embarazo/la lactancia.",
    "P264": "Lavarse... concienzudamente tras la manipulación.",
    "P270": "No comer, beber ni fumar durante su utilización.",
    "P271": "Utilizar únicamente en exteriores o en un lugar bien ventilado.",
    "P272": "Los materiales contaminados deben lavarse antes de volver a usarse.",
    "P273": "Evitar su liberación al medio ambiente.",
    "P280": "Llevar guantes/prendas/gafas/máscara de protección.",
    "P281": "Utilizar el equipo de protección individual requerido.",
    "P282": "Llevar equipo de protección ocular/equipo de protección facial.",
    "P283": "Llevar ropa resistente al fuego/retardante de llama.",
    "P284": "Llevar equipo de protección respiratoria.",
    "P285": "En caso de ventilación insuficiente, llevar equipo de protección respiratoria.",
    "P231+P232": "Manipular bajo gas inerte. Proteger de la humedad.",
    "P235+P410": "Mantener en lugar fresco. Proteger de la luz del sol.",
    "P370+P378": "En caso de incendio: Utilizar... para la extinción.",
    "P301": "EN CASO DE INGESTIÓN:...",
    "P302": "EN CASO DE CONTACTO CON LA PIEL:...",
    "P303": "EN CASO DE CONTACTO CON LA PIEL (o el cabello):...",
    "P304": "EN CASO DE INHALACIÓN:...",
    "P305": "EN CASO DE CONTACTO CON LOS OJOS:...",
    "P306": "EN CASO DE CONTACTO CON LA ROPA:...",
    "P307": "EN CASO de exposición:...",
    "P308": "EN CASO de exposición manifiesta o presunta:...",
    "P309": "EN CASO de exposición o malestar:...",
    "P310": "Llamar inmediatamente a un CENTRO DE TOXICOLOGÍA/médico/...",
    "P311": "Llamar a un CENTRO DE TOXICOLOGÍA/médico/...",
    "P312": "Llamar a un CENTRO DE TOXICOLOGÍA o a un médico si se encuentra mal.",
    "P313": "Consultar a un médico.",
    "P314": "Consultar a un médico en caso de malestar.",
    "P315": "Consultar inmediatamente a un médico.",
    "P320": "Tratamiento específico urgente (véase... en esta etiqueta).",
    "P321": "Tratamiento específico (véase... en esta etiqueta).",
    "P322": "Medidas específicas (véanse... en esta etiqueta).",
    "P330": "Enjuagarse la boca.",
    "P331": "NO provocar el vómito.",
    "P332": "En caso de irritación cutánea:...",
    "P333": "En caso de irritación o erupción cutánea:...",
    "P334": "Sumergir en agua fría/envuelva con vendas húmedas.",
    "P335": "Cepillar la materia desprendida de la piel.",
    "P336": "Descongelar las partes congeladas con agua tibia. No frotar la zona afectada.",
    "P337": "Si persiste la irritación ocular:...",
    "P338": "Quitar las lentes de contacto, si lleva y resulta fácil. Seguir aclarando.",
    "P340": "Trasladar a la persona al aire libre y mantenerla en una posición que le facilite la respiración.",
    "P341": "Si experimenta dificultades respiratorias, trasladar a la persona al aire libre y mantenerla en una posición que le facilite la respiración.",
    "P342": "En caso de síntomas respiratorios:...",
    "P350": "Lavar con abundante agua y jabón...",
    "P351": "Aclarar cuidadosamente con agua durante varios minutos.",
    "P352": "Lavar con abundante agua/...",
    "P353": "Aclarar la piel con agua/ducharse.",
    "P360": "Aclarar inmediatamente la piel contaminada con agua antes de quitarse la ropa.",
    "P361": "Quitar inmediatamente toda la ropa contaminada.",
    "P362": "Quitar la ropa contaminada.",
    "P363": "Lavar la ropa contaminada antes de volver a usarla.",
    "P364": "Y lavar antes de volver a usar.",
    "P370": "En caso de incendio:...",
    "P371": "En caso de incendio importante y si es seguro hacerlo:...",
    "P372": "Riesgo de explosión en caso de incendio.",
    "P373": "NO apagar el fuego si el incendio alcanza productos explosivos.",
    "P374": "Apagar el incendio desde una distancia prudente tomando las precauciones adecuadas.",
    "P375": "Evacuar la zona.",
    "P376": "Detener la fuga si puede hacerse sin riesgo.",
    "P377": "Fuga de gas en ignición: no apagar, salvo que la fuga pueda detenerse de forma segura.",
    "P378": "Utilizar... para la extinción.",
    "P380": "Evacuar la zona.",
    "P381": "Eliminar todas las fuentes de ignición si puede hacerse de forma segura.",
    "P390": "Absorber el vertido para evitar daños materiales.",
    "P391": "Recoger el vertido.",
    "P401": "Almacenar... (condiciones específicas que se indicarán).",
    "P402": "Almacenar en un lugar seco.",
    "P403": "Almacenar en un lugar bien ventilado.",
    "P404": "Almacenar en un recipiente cerrado.",
    "P405": "Guardar bajo llave.",
    "P406": "Almacenar en un recipiente resistente a la corrosión/... con un revestimiento interior adecuado.",
    "P407": "Mantener una distancia adecuada entre los montones de productos para evitar el riesgo de autocalentamiento.",
    "P410": "Proteger de la luz del sol.",
    "P411": "Almacenar a temperaturas no superiores a... ºC/... ºF.",
    "P412": "No exponer a temperaturas superiores a 50 ºC/122 ºF.",
    "P420": "Almacenar lejos de otros materiales.",
    "P422": "Almacenar el contenido bajo... (líquido adecuado).",
    "EUH001": "Explosivo en estado seco.",
    "EUH006": "Peligro de explosión con y sin contacto con el aire.",
    "EUH014": "Reacciona violentamente con el agua.",
    "EUH018": "Durante el uso puede formarse una mezcla vapor-aire explosiva/inflamable.",
    "EUH019": "Puede formar peróxidos explosivos.",
    "EUH044": "Riesgo de explosión si se calienta en estado confinado.",
    "EUH029": "En contacto con el agua libera gases tóxicos.",
    "EUH031": "En contacto con ácidos libera gases tóxicos.",
    "EUH032": "En contacto con ácidos libera gases muy tóxicos.",
    "EUH066": "La exposición repetida puede provocar sequedad o formación de grietas en la piel.",
    "EUH070": "Tóxico por contacto ocular.",
    "EUH071": "Corrosivo para las vías respiratorias.",
    "EUH201": "Contiene plomo. No utilizar en objetos que puedan chupar los niños.",
    "EUH201A": "Advertencia: contiene plomo.",
    "EUH202": "Cianocrilato. Peligro. Se pega a la piel y a los ojos en cuestión de segundos. Manténgase fuera del alcance de los niños.",
    "EUH203": "Contiene cromo (VI). Puede provocar una reacción alérgica.",
    "EUH204": "Contiene isocianatos. Puede provocar una reacción alérgica.",
    "EUH205": "Contiene compuestos epoxídicos. Puede provocar una reacción alérgica.",
    "EUH206": "Atención! No utilizar junto con otros productos. Puede desprender gases peligrosos (cloro).",
    "EUH207": "¡Precaución! Contiene cadmio. Durante su empleo se liberan humos peligrosos. Ver la información facilitada por el fabricante. Atenerse a las instrucciones de seguridad.",
    "EUH208": "Contiene (nombre de la sustancia sensibilizante). Puede provocar una reacción alérgica.",
    "EUH209": "Puede inflamarse en contacto con el aire.",
    "EUH209A": "Puede inflamarse en contacto con el aire.",
    "EUH210": "Ficha de datos de seguridad disponible a petición.",
    "EUH401": "Para evitar riesgos para la salud humana y el medio ambiente, siga las instrucciones de uso."
}

